### ISSUE TITLE
Route `/` on the central app always returns 404

### ISSUE THREAD

**Issue by abishekrsrikaanth** [stancl/tenancy#859]
### Bug description

The `/` route on the central app always returns 404. I looked into the stack trace and looks like the middleware `PreventAccessFromCentralDomains` is being triggered for domains configured on `tenancy.central_domains` as well. I am not sure if it is because the tenancy middlewares have a higher priority as defined on the `TenancyServiceProvider` but I can't seem to get `/` to work on the central domain. I tried to ask around on the discord channel and my advice was to have a unique name for the central route, but that did not fix either.

### Steps to reproduce

Here is my route file for the central app

**routes/web.php**
```php
Route::get('/', function () {
    return view('welcome');
})->name('central.root');
```

and here is the route for the tenancy
**routes/tenant.php**
```php
Route::middleware([
    'web',
    'universal',
    InitializeTenancyByDomainOrSubdomain::class,
    PreventAccessFromCentralDomains::class,
])->group(function () {
    Route::controller(HomeController::class)->group(function () {
        Route::get('/', 'index')->name('tenant.home');
    });
});
```

### Expected behavior

The `/` route on the central app should show the view/controller configured on the route file.

### Laravel version

9.12.2

### stancl/tenancy version

3.5.6

**Comment by abishekrsrikaanth** [comment]
Resolved this with the help of @realtydev. One of the packages that I was using had a `/` route which was causing the 404 error. Closing this issue.

**Comment by haovd** [comment]
@abishekrsrikaanth 
How did you do to fix this?

**Comment by sameervirus** [comment]
+1 how did you fix this

**Comment by dwicahyo-dev** [comment]
+1 how did you fix this @abishekrsrikaanth

**Comment by ezani92** [comment]
@stancl this still happening on fresh install. need your help

**Comment by itskawsar** [comment]
to fix this issue move this line `App\Providers\TenancyServiceProvider::class, ` to the bottom of `'providers'` array in `Config/App.php`

**Comment by shazeedul** [comment]
@stancl still facing 404 error

**Comment by stancl** [comment]
https://tenancyforlaravel.com/docs/v3/routes/#conflicting-paths
